spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dopamine_detox?serverTimezone=Asia/Seoul
    username: root
    password: wldnd3513
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: dnjswldnd-3513-jwt-bcsd-key-3513
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
